apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml 
    path: exercises/helm-exercise
    repoURL: https://github.com/anushkadeshpande/Cloud-Native-Coursework
    targetRevision: HEAD
